"""Database-related constants."""

ACTIVITY_KIND_READING_SESSION = "reading_session"
ACTIVITY_KIND_REVIEW_THEORY = "review_theory"
ACTIVITY_KIND_REVIEW_ALGORITHM_THEORY = "review_algorithm_theory"
ACTIVITY_KIND_ALGORITHM_TRAINING_TYPING = "algorithm_training_typing"
ACTIVITY_KIND_ALGORITHM_TRAINING_MEMORY = "algorithm_training_memory"

USER_ACTIVITY_KINDS: tuple[str, ...] = (
    ACTIVITY_KIND_READING_SESSION,
    ACTIVITY_KIND_REVIEW_THEORY,
    ACTIVITY_KIND_REVIEW_ALGORITHM_THEORY,
    ACTIVITY_KIND_ALGORITHM_TRAINING_TYPING,
    ACTIVITY_KIND_ALGORITHM_TRAINING_MEMORY,
)

ACTIVITY_STATUS_COMPLETED = "completed"
ACTIVITY_STATUS_ABORTED = "aborted"
ACTIVITY_STATUS_IMPORTED = "imported"

USER_ACTIVITY_STATUSES: tuple[str, ...] = (
    ACTIVITY_STATUS_COMPLETED,
    ACTIVITY_STATUS_ABORTED,
    ACTIVITY_STATUS_IMPORTED,
)

ACTIVITY_SOURCE_LIVE = "live"
ACTIVITY_SOURCE_IMPORT = "import"
ACTIVITY_SOURCE_BACKFILL = "backfill"

USER_ACTIVITY_SOURCES: tuple[str, ...] = (
    ACTIVITY_SOURCE_LIVE,
    ACTIVITY_SOURCE_IMPORT,
    ACTIVITY_SOURCE_BACKFILL,
)

